name: Sync with Upstream

on:
  workflow_dispatch:
    inputs:
      upstream_url:
        description: "Specify the upstream repository URL"
        required: true

jobs:
  sync-upstream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Backup workflows
        run: |
          mkdir -p /tmp/workflows-backup
          cp -r .github/workflows /tmp/workflows-backup/

      - name: Add upstream repository
        run: |
          git remote add upstream ${{ github.event.inputs.upstream_url }}

      - name: Fetch upstream
        run: |
          git fetch upstream

      - name: Reset to upstream
        run: |
          git reset --hard upstream/main

      - name: Restore workflows
        run: |
          mkdir -p .github/workflows
          cp -r /tmp/workflows-backup/. .github/workflows/
          git add .github/workflows
          git diff --staged --quiet || git commit -m "Restore all workflows after upstream sync"

      - name: Push to origin
        run: |
          git push --force origin main
        continue-on-error: true

      - name: Check push status
        run: |
          if [ $? -ne 0 ]; then
            echo "Force push failed"
            exit 1
          fi
